services:
    app:
      build: .
      command: python -u Girito/web/webapp/app.py
      ports:
        - "5000:5000"
      networks:
        vpcbr:
          ipv4_address: 10.5.0.5
      volumes:
        - .:/app
      links:
        - db

    db:
      image: mongo:latest
      hostname: mongodb
      environment: 
        - MONGODB_DATABASE=live_feed_astronomy
      networks:
        vpcbr:
          ipv4_address: 10.5.0.6
      ports:
        - "27017:27017"
      volumes:
       - ./DBdata:/data/db

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1